server:
  port: 8081

jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600


spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: prod