server:
  port: 10000

spring:
#  application:
#    name: gateway-service  #应用名称
  cloud:
    gateway:
        add-to-simple-url-handler-mapping: true
    nacos:         #nacos配置
      discovery:
        namespace: dev  #命名空间
        server-addr: localhost:8848   #nacos端口
#        heart-beat-timeout: 5000
#        heart-beat-interval: 20000
        # group: DEV_GROUP
        register-enabled: true

