server:
  port: 8084

spring:
  application:
    name: file-service
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.178.129:8848
        namespace: dev
      config:
        server-addr: 124.222.178.129:8848
        file-extension: yml
        namespace: dev
        group: DEFAULT_GROUP
        timeout: 5000
        config-long-poll-timeout: 10000
        config-retry-time: 2000
        max-retry: 3
        refresh-enabled: true
        # prefix: hello
      username: nacos
      password: nacos